In [3]:
import numpy as np

# intro

In [2]:
list1=list(range(1000000))

In [3]:
np_array=np.arange(1000000)

In [4]:
%timeit list1*3

35.8 ms ± 931 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [5]:
%timeit np_array*3

3.22 ms ± 143 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# Creating Ndarrays

In [22]:
np_array_2=np.random.randn(2,3,2)

In [23]:
np_array_2

array([[[ 0.79378536,  0.17657363],
        [-0.60258239, -0.39606671],
        [-1.5051163 , -0.2873536 ]],

       [[ 0.14537771,  0.27329664],
        [-0.95562557, -0.52689641],
        [-1.39242121, -0.62643179]]])

In [21]:
np_array_2.ndim

2

In [16]:
np_array_2.shape

(2, 3)

In [17]:
np_array_2.dtype

dtype('float64')

In [24]:
lista=[1,2,5,6]

In [26]:
array=np.array(lista)

In [27]:
array

array([1, 2, 5, 6])

In [28]:
array.ndim

1

In [29]:
array.shape

(4,)

In [30]:
list_2=[[1,2,3],[1,2,3]]

In [31]:
array_2=np.array(list_2)

In [32]:
array_2

array([[1, 2, 3],
       [1, 2, 3]])

In [35]:
array_2.ndim

2

In [36]:
array_2.shape

(2, 3)

In [25]:
array_3=np.zeros((3,3))
array_3

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
array_4=np.ones((3,3))
array_4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

# change datatype

In [30]:
list_2=[[1,2,3],[1,2,3]]

In [31]:
array_2=np.array(list_2)
array_float=array_2.astype(np.float64)
array_float

array([[1., 2., 3.],
       [1., 2., 3.]])

In [32]:
list_2=["1","5","6","18"]
array=np.array(list_2)

In [33]:
array-5

UFuncTypeError: ufunc 'subtract' did not contain a loop with signature matching types (dtype('<U2'), dtype('int32')) -> None

In [39]:
arrayInt=array.astype(np.int16)

In [40]:
arrayInt-5

array([-4,  0,  1, 13], dtype=int16)

# Arithmetic with NumPy Arrays

In [54]:
list1=[[1,2,3],[1,2,3]]
array=np.array(list1)
array

array([[1, 2, 3],
       [1, 2, 3]])

In [55]:
array * array     #element wise 

array([[1, 4, 9],
       [1, 4, 9]])

In [56]:
array- array

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
array *5

array([[ 5, 10, 15],
       [ 5, 10, 15]])

In [58]:
array ** 0.5

array([[1.        , 1.41421356, 1.73205081],
       [1.        , 1.41421356, 1.73205081]])

In [59]:
array >5

array([[False, False, False],
       [False, False, False]])

# Indexing and Slicing-Part One

In [55]:
array=np.arange(2,20,2)

In [48]:
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [56]:
array[4]

10

In [49]:
array[2:8]

array([ 6,  8, 10, 12, 14, 16])

In [57]:
slice=array[3:]
# slice[0]=99
slice

array([ 8, 10, 12, 14, 16, 18])

In [58]:
array

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [66]:
slice1=array[3:].copy()
slice1[0]=99


array([[99, 99, 99]])

array([[19, 23, 39],
       [ 1, 26,  4],
       [21,  5, 18],
       [ 6, 11, 16]])

In [68]:
array=np.array([[19,23,39],[1,26,4],[21,5,18],[6,11,16]])     # 2d array 
array 

array([[19, 23, 39],
       [ 1, 26,  4],
       [21,  5, 18],
       [ 6, 11, 16]])

In [70]:
array[0:2,0:1]     # slicing rows ,slicing columns

array([[19],
       [ 1]])

In [71]:
array[2,1]

5

# Boolean Indexing

In [156]:
array1=np.array(["a","b","a","c","d","a","f"])
array1

array(['a', 'b', 'a', 'c', 'd', 'a', 'f'], dtype='<U1')

In [157]:
array2=np.array([1,6,5,22,30,69,16])
array2

array([ 1,  6,  5, 22, 30, 69, 16])

In [158]:
array1=="a"

array([ True, False,  True, False, False,  True, False])

In [159]:
array2[array1=="a"]

array([ 1,  5, 69])

In [160]:
array3=np.random.randn(7,2)
array3

array([[ 0.03396309, -0.91437553],
       [ 0.84660205, -0.13612122],
       [ 0.45844503, -0.52957425],
       [ 0.37348633, -1.45081421],
       [ 1.33090413, -2.40320372],
       [ 0.82806894, -2.96774416],
       [-0.43362013,  0.59541921]])

In [161]:
array3[array1=="a"]

array([[ 0.03396309, -0.91437553],
       [ 0.45844503, -0.52957425],
       [ 0.82806894, -2.96774416]])

In [163]:
array4=np.array([[1,3],[5,8],[56,30],[1,30],[5,5],[1,6]])
array4

array([[ 1,  3],
       [ 5,  8],
       [56, 30],
       [ 1, 30],
       [ 5,  5],
       [ 1,  6]])

In [164]:
array4.shape

(6, 2)

In [168]:
array4[array4[:,0]==1]

array([[ 1,  3],
       [ 1, 30],
       [ 1,  6]])

# Fancy Indexing

In [172]:
array=np.random.randint(50,size=10)
array

array([45,  9, 13, 23, 37, 10,  6, 38, 23, 35])

In [174]:
index=[1,3,5,7]
array[index]

array([ 9, 23, 10, 38])

In [179]:
index=np.array([[1,3],[5,7]])
array[index]

array([[ 9, 23],
       [10, 38]])

In [184]:
array=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [185]:
ind=((0,1,2,3),(1,2,3,0))

In [186]:
array[ind]

array([ 2,  7, 12, 13])

In [187]:
array[[0,1,2,3],[1,2,3,0]]

array([ 2,  7, 12, 13])

# Transposing Arrays

In [188]:
array=np.random.randint(20,size=(3,4))
array

array([[ 7,  5, 14, 10],
       [12, 18,  3, 16],
       [10, 16,  2, 17]])

In [189]:
array.transpose()

array([[ 7, 12, 10],
       [ 5, 18, 16],
       [14,  3,  2],
       [10, 16, 17]])

In [190]:
array.T

array([[ 7, 12, 10],
       [ 5, 18, 16],
       [14,  3,  2],
       [10, 16, 17]])

# Mathematical and Statistical Methods

In [193]:
array=np.random.randn(3,4)
array

array([[-0.40272961, -1.23836311, -0.46339626, -0.74120327],
       [ 0.86859904, -0.0176813 ,  0.73230416,  0.47060415],
       [ 0.2440459 ,  0.44178246,  2.19262677,  0.37804081]])

In [194]:
array.mean()

0.20538581219998386

In [195]:
np.mean(array)

0.20538581219998386

In [196]:
array.max()

2.192626771087839

In [197]:
array.min()

-1.2383631075201589

In [198]:
array.std()

0.8500698222210623

In [200]:
array.argmin()

1

In [201]:
array.argmax()

10

In [202]:
array

array([[-0.40272961, -1.23836311, -0.46339626, -0.74120327],
       [ 0.86859904, -0.0176813 ,  0.73230416,  0.47060415],
       [ 0.2440459 ,  0.44178246,  2.19262677,  0.37804081]])

In [205]:
array.sum(axis=0)   # zero for rows and one for columns

array([ 0.70991533, -0.81426195,  2.46153467,  0.10744169])

In [207]:
array1=np.array([True,False,True,False,True])
array1.sum()

3

In [209]:
array1.any()

True

In [212]:
array1.all()

False

# Sorting Arrays

In [215]:
array=np.random.randn(5)
array

array([-0.74848224, -0.48763432,  0.78863416, -0.4405042 , -1.23997275])

In [219]:
array.sort()
array

array([-1.23997275, -0.74848224, -0.48763432, -0.4405042 ,  0.78863416])

In [220]:
np.sort(array)
array

array([-1.23997275, -0.74848224, -0.48763432, -0.4405042 ,  0.78863416])

In [222]:
np.sort(array)[::-1]   # in descending order 

array([ 0.78863416, -0.4405042 , -0.48763432, -0.74848224, -1.23997275])

# File Input and Output with Arrays

In [225]:
array=np.arange(10)
array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [226]:
np.save("array",array)

In [228]:
np.load("array.npy")

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [230]:
array2=np.arange(20)

In [231]:
np.savez("arrays.npz",a1=array,a2=array2)

In [236]:
np.load("arrays.npz")["a2"]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])